[phases.setup]
nixPkgs = ["python310", "gcc", "chromium", "chromedriver"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn backend.fastapi_app:app --host 0.0.0.0 --port $PORT"

[variables]
CHROME_BIN = "/nix/store/*/bin/chromium"
CHROMEDRIVER_PATH = "/nix/store/*/bin/chromedriver"
