services:
  - type: web
    runtime: docker
    name: listing-bot-api
    region: ohio
    plan: starter  # Required for Docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    buildCommand: ''  # Docker handles build
    startCommand: ''  # Defined in Dockerfile
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11  # Handled in Dockerfile
      # Add your marketplace credentials here
      - key: HUBX_USERNAME
        sync: false
      - key: HUBX_PASSWORD
        sync: false
      - key: GSMEXCHANGE_USERNAME
        sync: false
      - key: GSMEXCHANGE_PASSWORD
        sync: false
      - key: KARDOF_USERNAME
        sync: false
      - key: KARDOF_PASSWORD
        sync: false
      - key: CELLPEX_USERNAME
        sync: false
      - key: CELLPEX_PASSWORD
        sync: false
      - key: HANDLOT_USERNAME
        sync: false
      - key: HANDLOT_PASSWORD
        sync: false
      - key: LINKEDIN_USERNAME
        sync: false
      - key: LINKEDIN_PASSWORD
        sync: false 